language: c

sudo: required

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA='Lua 5.1'
    - LUA='Lua 5.2'
    - LUA='Lua 5.3'
    - LUA='LuaJIT 2.0'

branches:
  only:
    - master

before_install:
  - bash .travis_setup.sh

install:
  - sudo apt-get update -qq
  - sudo luarocks install luacov-coveralls
  - sudo luarocks install busted

script:
  - busted -v -c

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
