version: 2
jobs:
  lua51:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - run:
          name: Unit tests
          command: nix-shell --run "LUA='lua=5.1' make -e tests"
      - run:
          name: Coverage
          command: nix-shell --run "make coverage"
  lua52:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - run:
          name: Unit tests
          command: nix-shell --run "LUA='lua=5.2' make -e tests"
      - run:
          name: Coverage
          command: nix-shell --run "make coverage"
  lua53:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - run:
          name: Unit tests
          command: nix-shell --run "LUA='lua=5.3' make -e tests"
      - run:
          name: Coverage
          command: nix-shell --run "make coverage"
  luajit21:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - run:
          name: Unit tests
          command: nix-shell --run "LUA='luajit=2.1' make -e tests"
      - run:
          name: Coverage
          command: nix-shell --run "make coverage"
