name: test-run

on: [push, pull_request]

jobs:
  build:
    if: ( github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != github.repository ) &&
        ( github.repository == 'luc-tielen/lua-quickcheck' )

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lua-version: ['lua=5.1', 'lua=5.2', 'luajit=2.0', 'luajit=2.1']

    steps:
    - uses: actions/checkout@v2

    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: setup hererocks ${{ matrix.lua-version }}
      run: |
        python -m pip install --upgrade pip
        pip install --user hererocks
        hererocks lua_install -r^ --${{ matrix.lua-version }} --verbose
        echo "${PWD}/lua_install/bin" | tee -a $GITHUB_PATH

    - name: setup dependencies
      run: |
        luarocks install argparse
        luarocks install luafilesystem
        luarocks install luacheck
        luarocks install luacov
        luarocks install luacov-coveralls
        luarocks install busted
        luarocks install lanes
        luarocks install moonscript
        if [[ $(echo ${{ matrix.lua-version }} | grep -o "jit") = "" ]]; then luarocks install luaffi --server=http://luarocks.org/dev; fi

    - name: run regression tests
      run: LUA=${{ matrix.lua-version }} make -e tests

    - name: upload code coverage
      if: ${{ success() }}
      run: luacov-coveralls -v -e $GITHUB_WORKSPACE/lua_install
